[workspace]
members = [
    "android-release-support",
    "rustls-platform-verifier",
]
resolver = "2"

[patch."crates-io"]
jni = { git = "https://github.com/jni-rs/jni-rs", branch = "release-0.22" }
